### ISSUE TITLE
Downloads with OKEY Doc not compatible with Joomla 3.8.0

### ISSUE THREAD

**Issue by jsweimar** [Duddy67/okey-doc#1]
OKEY Doc works fine with Joomla Version 3.7.5 but not with 3.8.0
Clicking on a download results in a blank page without any action.

**Comment by Duddy67** [comment]
Okey Doc code has just been updated and tested for the Joomla 3.8 version and everything works fine. I'd need more infos regarding the problem you're running into. Is that problem occurs from backend, frontend ? Do you have the proper rights on the server ? Could you provide screenshots ?

**Comment by jsweimar** [comment]
This problem occurs as soon as I update to version 3.8.0 
By clicking on the download file (backend and frontend) a new blank page opens with the download link in the adress line but nothing happens. 
![image](https://user-images.githubusercontent.com/32510085/31176150-1e58ed7e-a912-11e7-8e1e-4c6cdd5e9aad.png)

**Comment by Duddy67** [comment]
Have you installed the Okey DOC package 1.6 available [here](https://github.com/Duddy67/okey-doc) in the Download section ?

**Comment by strickerat** [comment]
I have the same issue: server reports a http-error 500 when trying to download documents from frontend after joomla-update to 3.8.0
Don't know which okeydoc package I have, it's about 18 months old and joomla never offered me any updates for it...

**Comment by jsweimar** [comment]
I actually installed the latest version like you told me but I still have this problem. I don't get any errors, just a blank site. But I also had to change the links. The starting folder for the path to the file is different.

**Comment by Duddy67** [comment]
What links did you change ? Can you show me a link to one of your document ?

**Comment by jsweimar** [comment]
These are the links for external URL in the backend of a file in my testing environment:
the actual link was ../downloads/Q/4.30/setup-server-bundle.zip
the new link is ../../../downloads/Q/4.30/setup-server-bundle.zip
so I needed to navigate two folders higher then before

**Comment by Duddy67** [comment]
These URL are not valid. An external URL should looks something like: 
http://websitedomain.com/downloads/Q/4.30/setup-server-bundle.zip

**Comment by jsweimar** [comment]
My bad, thanks a lot! 
It works perfectly fine in my testing environment now. I will try it in my life web page.
You can close this issue.
